In [48]:
import numpy as np

In [49]:
A=np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])
B=np.array([[4,1,1,1],[1,3,-1,1],[1,-1,2,0],[1,1,0,2]])
C=np.array([[4,1,-1,0],[1,3,-1,0],[-1,-1,5,2],[0,0,2,4]])
D=np.array([[6,2,1,-1],[2,4,1,0],[1,1,4,-1],[-1,0,-1,3]])



In [50]:
NMatrices=["A","B","C","D"]
Matrices=[A,B,C,D]

In [95]:
def LDL(x):
    l=np.linalg.cholesky(x)
    d=(np.diag(x))
    n=len(x)
    D=np.zeros([n,n])
    for k in range(n):
        for r in range(n):
            if (k == r):
                l[k, r] = 1
    
    for i in range(n):
        for j in range(n):
            if (i == j):
                D[i, j]= d[j]
            else: pass
    print(l)
    print(D)
    print(np.transpose(l))



In [96]:
for i in range(len(NMatrices)):
    m=NMatrices[i]
    print("La factorización de la matriz " +NMatrices[i]+ " es") 
    L=np.linalg.cholesky(Matrices[i])
    print(NMatrices[i],"=")
    print(L)
    print(np.transpose(L))


La factorización de la matriz A es
A =
[[ 1.41421356  0.          0.        ]
 [-0.70710678  1.22474487  0.        ]
 [ 0.         -0.81649658  1.15470054]]
[[ 1.41421356 -0.70710678  0.        ]
 [ 0.          1.22474487 -0.81649658]
 [ 0.          0.          1.15470054]]
La factorización de la matriz B es
B =
[[ 2.          0.          0.          0.        ]
 [ 0.5         1.6583124   0.          0.        ]
 [ 0.5        -0.75377836  1.08711461  0.        ]
 [ 0.5         0.45226702  0.0836242   1.24034735]]
[[ 2.          0.5         0.5         0.5       ]
 [ 0.          1.6583124  -0.75377836  0.45226702]
 [ 0.          0.          1.08711461  0.0836242 ]
 [ 0.          0.          0.          1.24034735]]
La factorización de la matriz C es
C =
[[ 2.          0.          0.          0.        ]
 [ 0.5         1.6583124   0.          0.        ]
 [-0.5        -0.45226702  2.13200716  0.        ]
 [ 0.          0.          0.93808315  1.76635217]]
[[ 2.          0.5        -0.5  

In [97]:
d=(np.diag(L))
print(d)

[2.44948974 1.82574186 1.92353841 1.60657433]


In [100]:
for i in range(len(NMatrices)):
    m=NMatrices[i]
    print("La factorización LL^t de la matriz " +NMatrices[i]+ " es") 
    L=np.linalg.cholesky(Matrices[i])
    print(NMatrices[i],"=")
    print(L)
    print(np.transpose(L))
    print("La factorización LDL^t de la matriz " +NMatrices[i]+ " es")
    print(NMatrices[i],"=")
    LDL(L)


La factorización LL^t de la matriz A es
A =
[[ 1.41421356  0.          0.        ]
 [-0.70710678  1.22474487  0.        ]
 [ 0.         -0.81649658  1.15470054]]
[[ 1.41421356 -0.70710678  0.        ]
 [ 0.          1.22474487 -0.81649658]
 [ 0.          0.          1.15470054]]
La factorización LDL^t de la matriz A es
A =
[[ 1.          0.          0.        ]
 [-0.59460356  1.          0.        ]
 [ 0.         -0.87477741  1.        ]]
[[1.41421356 0.         0.        ]
 [0.         1.22474487 0.        ]
 [0.         0.         1.15470054]]
[[ 1.         -0.59460356  0.        ]
 [ 0.          1.         -0.87477741]
 [ 0.          0.          1.        ]]
La factorización LL^t de la matriz B es
B =
[[ 2.          0.          0.          0.        ]
 [ 0.5         1.6583124   0.          0.        ]
 [ 0.5        -0.75377836  1.08711461  0.        ]
 [ 0.5         0.45226702  0.0836242   1.24034735]]
[[ 2.          0.5         0.5         0.5       ]
 [ 0.          1.6583124  -0.7