In [6]:
import numpy as np
from numpy import linalg as LA

In [67]:
def Householder(A):
    Ai = np.copy(A)
    nRen, nCol = A.shape
    q = list()
    for i in range(nCol):
        x = np.array(Ai[:, i])
        e = 0
        for j in range(i):
            x[j] = 0
            e += 1
        u = x+(np.sign(Ai[i, i])*LA.norm(x)*np.eye(len(Ai))[:, e])
        v = u/LA.norm(u)
        vt = v.reshape((len(v), 1))
        H = np.eye(len(Ai))-2*np.matmul(vt, vt.T)
        Ai = np.matmul(H, Ai)
        q.append(H)
    R = Ai
    Q = q[0]
    for k in range(1, len(q)):
        Q = np.matmul(Q, q[k])
    return Q, R

In [68]:
def EC_normales(A, b):
    At=np.transpose(A)
    AtA=np.matmul(At, A)
    Atb=np.matmul(At, b)
    return AtA, Atb

In [69]:
def sustitucion(A, b):
    n = A.shape[1]
    x = [0]*n
    for i in range(n-1, -1, -1):
        for j in range(i+1, n):
            b[i] = b[i] - A[i, j]*x[j]
        x[i] = b[i]/A[i, i]

    return x

In [74]:
e=np.sqrt(np.finfo(float).eps)
e_1=np.finfo(float).eps
e_2=2*(np.finfo(float).eps)
print(e)
A=np.array([[1,1,1],[e,0,0],[e,0,0],[e,0,0]])
A_1=np.array([[1,1,1],[e_1,0,0],[e_1,0,0],[e_1,0,0]])
A_2=np.array([[1,1,1],[e_2,0,0],[e_2,0,0],[e_2,0,0]])
b=np.array([[1],[0],[0],[0]])
print(A)

1.4901161193847656e-08
[[1.00000000e+00 1.00000000e+00 1.00000000e+00]
 [1.49011612e-08 0.00000000e+00 0.00000000e+00]
 [1.49011612e-08 0.00000000e+00 0.00000000e+00]
 [1.49011612e-08 0.00000000e+00 0.00000000e+00]]


In [58]:
print(sustitucion(EC_normales(A, b)[0], EC_normales(A, b)[1]))
print(sustitucion(EC_normales(A_1, b)[0], EC_normales(A_1, b)[1]))
print(sustitucion(EC_normales(A_2, b)[0], EC_normales(A_2, b)[1]))

[array([0.]), array([0.]), array([1.])]
[array([0.]), array([0.]), array([1.])]
[array([0.]), array([0.]), array([1.])]


In [65]:
Qt = np.transpose(Householder(A)[0])
R = Householder(A)[1]
print(sustitucion())
print(sustitucion())
print(sustitucion())

TypeError: Householder() missing 1 required positional argument: 'b'

In [72]:
Householder(A)

C:\Users\KR\AppData\Local\Temp\ipykernel_14168\4190480536.py:12: RuntimeWarning: invalid value encountered in divide
  v = u/LA.norm(u)


(array([[nan, nan, nan, nan],
        [nan, nan, nan, nan],
        [nan, nan, nan, nan],
        [nan, nan, nan, nan]]),
 array([[nan, nan, nan],
        [nan, nan, nan],
        [nan, nan, nan],
        [nan, nan, nan]]))

In [91]:
import numpy as np

def column_convertor(x):
    """
    Converts 1d array to column vector
    """
    x.shape = (1, x.shape[0])
    return x

def get_norm(x):
    """
    Returns Norm of vector x
    """
    return np.sqrt(np.sum(np.square(x)))

def householder_transformation(v):
    """
    Returns Householder matrix for vector v
    """
    size_of_v = v.shape[1]
    e1 = np.zeros_like(v)
    e1[0, 0] = 1
    vector = get_norm(v) * e1
    if v[0, 0] < 0:
        vector = - vector
    u = (v + vector).astype(np.float32)
    H = np.identity(size_of_v) - ((2 * np.matmul(np.transpose(u), u)) / np.matmul(u, np.transpose(u)))
    return H

def qr_step_factorization(q, r, iter, n):
    """
    Return Q and R matrices for iter number of iterations.
    """
    v = column_convertor(r[iter:, iter])
    Hbar = householder_transformation(v)
    H = np.identity(n)
    H[iter:, iter:] = Hbar
    r = np.matmul(H, r)
    q = np.matmul(q, H)
    return q, r

def main():
    
    A = np.array([[1,1,1],[e,0,0],[e,0,0],[e,0,0]])
    n,m =A.shape
    Q = np.identity(n)
    R = A.astype(np.float32)
    for i in range(min(n, m)):
        # For each iteration, H matrix is calculated for (i+1)th row
        Q, R = qr_step_factorization(Q, R, i, n)
    min_dim = min(m, n)
    print(R)
    print(Q)


if __name__ == "__main__":
    main()

[[-1.00000000e+00 -1.00000000e+00 -1.00000000e+00]
 [ 5.73087588e-24  2.58095696e-08  2.58095696e-08]
 [-2.02617029e-24  6.28036999e-16  6.28036999e-16]
 [ 1.16981009e-24 -1.32348898e-23 -1.32348898e-23]]
[[-1.00000000e+00  2.58095696e-08  6.28036999e-16 -1.32348898e-23]
 [-1.49011612e-08 -5.77350378e-01  8.16496587e-01 -1.72063785e-08]
 [-1.49011612e-08 -5.77350259e-01 -4.08248344e-01 -7.07106775e-01]
 [-1.49011612e-08 -5.77350259e-01 -4.08248285e-01  7.07106793e-01]]
