In [2]:
import numpy as np
from numpy import linalg as LA

In [3]:
def Householder_Q(A):
  Ai=np.copy(A)
  nRen,nCol = A.shape
  q=list()
  for i in range(nCol):
    x=np.array(Ai[:,i])
    e=0
    for j in range(i):
      x[j]=0
      e+=1
    u=x+(np.sign(Ai[i,i])*LA.norm(x)*np.eye(len(Ai))[:,e])
    v=u/LA.norm(u)
    vt=v.reshape((len(v),1))
    H=np.eye(len(Ai))-2*np.matmul(vt,vt.T)
    Ai=np.matmul(H,Ai)
    q.append(H)
  R=Ai
  Q=q[0]
  for k in range(1,len(q)):
    Q=np.matmul(Q,q[k])
  return Q, R

In [10]:
matriz = np.array([[0.16, 0.10], [0.17, 0.11], [2.02, 1.29]])
b=np.array([[0.26],[0.28],[3.31]])

In [117]:
Qt=np.transpose(Householder_Q(matriz)[0])
print(Qt)
R=Householder_Q(matriz)[1]
print(R)
b_prima = np.matmul(Qt,b)
print(b_prima)

[[-0.07868419 -0.08360195 -0.9933879 ]
 [ 0.83357047 -0.55206658 -0.01956433]
 [-0.54678064 -0.82959822  0.11312703]]
[[-2.03344535e+00 -1.29853502e+00]
 [-2.12228712e-16 -2.60826889e-03]
 [ 1.36607858e-16 -7.06718282e-20]]
[[-3.33198037e+00]
 [-2.60826889e-03]
 [ 1.66533454e-16]]


In [54]:
R[1][]

-0.002608268885602783

In [65]:
def sustitucion(R , b):
    R.transpose()
    b.transpose()
    n=R.shape[1]
    x=np.zeros(n-1)
    for i in range(n-1,0-1,-1 ):
        s=np.dot(R[i][i+1:], x[i+1:])
        x[i]=(b[i]-s)/R[i,i]
    return x

In [119]:
def sustitucion(R , b):
    n=R.shape[1]
    x = [0]*n
    for i in range(n-1,-1,-1):
        for j in range(i+1,n): 
            b[i] = b[i] - R[i,j]*x[j]
        x[i] = b[i]/R[i,i]
          
    return x

In [120]:
sustitucion(R,b_prima)

[array([0.3614114]), array([1.])]